services:
  pig-mysql:
    image: registry.cn-hangzhou.aliyuncs.com/dockerhub_mirror/mysql-server:8.0.32
    pull_policy: if_not_present
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
    restart: "no"
    container_name: pig-mysql
    ports:
      - 33306:3306
    volumes:
      - ./db/pig.sql:/docker-entrypoint-initdb.d/01-pig.sql:ro
      - ./db/pig_config.sql:/docker-entrypoint-initdb.d/02-pig_config.sql:ro
    networks:
      - spring_cloud_default

  pig-phpmyadmin:
    image: phpmyadmin:latest
    restart: "no"
    container_name: pig-phpmyadmin
    hostname: pig-phpmyadmin
    ports:
      - 8082:80
    environment:
      PMA_HOST: pig-mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      pig-mysql:
        condition: service_healthy
    networks:
      - spring_cloud_default

  pig-redis:
    image: registry.cn-hangzhou.aliyuncs.com/dockerhub_mirror/redis
    ports:
      - 36379:6379
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    restart: "no"
    container_name: pig-redis
    hostname: pig-redis
    networks:
      - spring_cloud_default

  pig-register:
    image: nacos/nacos-server:v2.4.3
    restart: "no"
    ports:
      - 8848:8848
      - 9848:9848
      - 8080:8080
    environment:
      MODE: standalone
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: pig-mysql
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_DB_NAME: pig_config
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: root
      MYSQL_SERVICE_DB_PARAM: characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      NACOS_AUTH_ENABLE: true
      NACOS_AUTH_IDENTITY_KEY: serverIdentity
      NACOS_AUTH_IDENTITY_VALUE: security
      NACOS_AUTH_TOKEN: VGhpc0lzTXlDdXN0b21TZWNyZXRLZXkwMTIzNDU2Nzg=
    container_name: pig-register
    hostname: pig-register
    depends_on:
      pig-mysql:
        condition: service_healthy
    networks:
      - spring_cloud_default

  pig-gateway:
    build:
      context: ./pig-gateway
    restart: "no"
    ports:
      - 9999:9999
    container_name: pig-gateway
    hostname: pig-gateway
    image: pig-gateway
    environment:
      REDIS_HOST: pig-redis
      NACOS_HOST: pig-register
    depends_on:
      pig-redis:
        condition: service_started
      pig-register:
        condition: service_started
    networks:
      - spring_cloud_default

  pig-auth:
    build:
      context: ./pig-auth
    restart: "no"
    container_name: pig-auth
    hostname: pig-auth
    image: pig-auth
    environment:
      REDIS_HOST: pig-redis
      NACOS_HOST: pig-register
    depends_on:
      pig-redis:
        condition: service_started
      pig-register:
        condition: service_started
    networks:
      - spring_cloud_default

  pig-upms:
    build:
      context: ./pig-upms/pig-upms-biz
    restart: "no"
    container_name: pig-upms
    hostname: pig-upms
    image: pig-upms
    volumes:
      - /home/luan/data/pig/files:/home/luan/data/pig/files
    environment:
      MYSQL_HOST: pig-mysql
      REDIS_HOST: pig-redis
      NACOS_HOST: pig-register
    depends_on:
      pig-mysql:
        condition: service_healthy
      pig-redis:
        condition: service_started
      pig-register:
        condition: service_started
    networks:
      - spring_cloud_default

  pig-takeaway-user:
    build:
      context: ./pig-takeaway/pig-takeaway-user/pig-takeaway-user-biz
    restart: "no"
    image: pig-takeaway-user
    container_name: pig-takeaway-user
    hostname: pig-takeaway-user
    environment:
      MYSQL_HOST: pig-mysql
      REDIS_HOST: pig-redis
      NACOS_HOST: pig-register
    depends_on:
      pig-mysql:
        condition: service_healthy
      pig-redis:
        condition: service_started
      pig-register:
        condition: service_started
    networks:
      - spring_cloud_default

  pig-takeaway-dish:
    build:
      context: ./pig-takeaway/pig-takeaway-dish/pig-takeaway-dish-biz
    restart: "no"
    image: pig-takeaway-dish
    container_name: pig-takeaway-dish
    hostname: pig-takeaway-dish
    environment:
      MYSQL_HOST: pig-mysql
      REDIS_HOST: pig-redis
      NACOS_HOST: pig-register
    depends_on:
      pig-mysql:
        condition: service_healthy
      pig-redis:
        condition: service_started
      pig-register:
        condition: service_started
    networks:
      - spring_cloud_default

  pig-takeaway-order:
    build:
      context: ./pig-takeaway/pig-takeaway-order/pig-takeaway-order-biz
    restart: "no"
    image: pig-takeaway-order
    container_name: pig-takeaway-order
    hostname: pig-takeaway-order
    environment:
      MYSQL_HOST: pig-mysql
      REDIS_HOST: pig-redis
      NACOS_HOST: pig-register
    depends_on:
      pig-mysql:
        condition: service_healthy
      pig-redis:
        condition: service_started
      pig-register:
        condition: service_started
    networks:
      - spring_cloud_default

  pig-takeaway-pay:
    build:
      context: ./pig-takeaway/pig-takeaway-pay/pig-takeaway-pay-biz
    restart: "no"
    image: pig-takeaway-pay
    container_name: pig-takeaway-pay
    hostname: pig-takeaway-pay
    environment:
      MYSQL_HOST: pig-mysql
      REDIS_HOST: pig-redis
      NACOS_HOST: pig-register
    depends_on:
      pig-mysql:
        condition: service_healthy
      pig-redis:
        condition: service_started
      pig-register:
        condition: service_started
    networks:
      - spring_cloud_default

networks:
  spring_cloud_default:
    name:  spring_cloud_default
    driver: bridge
