services:
  pig-mysql:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: pig-mysql
    image: pig-mysql
    ports:
      - 33306:3306
    networks:
      - spring_cloud_default

  pig-redis:
    image: registry.cn-hangzhou.aliyuncs.com/dockerhub_mirror/redis
    ports:
      - 36379:6379
    restart: always
    container_name: pig-redis
    hostname: pig-redis
    networks:
      - spring_cloud_default

  pig-register:
    image: nacos/nacos-server:v2.4.3
    restart: always
    ports:
      - 8848:8848
      - 9848:9848
      - 8080:8080
    environment:
      MODE: standalone
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: pig-mysql
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_DB_NAME: pig_config
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: root
      MYSQL_SERVICE_DB_PARAM: characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      NACOS_AUTH_ENABLE: true
      NACOS_AUTH_IDENTITY_KEY: serverIdentity
      NACOS_AUTH_IDENTITY_VALUE: security
      NACOS_AUTH_TOKEN: VGhpc0lzTXlDdXN0b21TZWNyZXRLZXkwMTIzNDU2Nzg=
    container_name: pig-register
    hostname: pig-register
    depends_on:
      pig-mysql:
        condition: service_healthy
    networks:
      - spring_cloud_default

  pig-gateway:
    build:
      context: ./pig-gateway
    restart: always
    ports:
      - 9999:9999
    container_name: pig-gateway
    hostname: pig-gateway
    image: pig-gateway
    environment:
      REDIS_HOST: pig-redis
      NACOS_HOST: pig-register
    depends_on:
      pig-redis:
        condition: service_started
      pig-register:
        condition: service_started
    networks:
      - spring_cloud_default

  pig-auth:
    build:
      context: ./pig-auth
    restart: always
    container_name: pig-auth
    hostname: pig-auth
    image: pig-auth
    environment:
      REDIS_HOST: pig-redis
      NACOS_HOST: pig-register
    depends_on:
      pig-redis:
        condition: service_started
      pig-register:
        condition: service_started
    networks:
      - spring_cloud_default

  pig-upms:
    build:
      context: ./pig-upms/pig-upms-biz
    restart: always
    container_name: pig-upms
    hostname: pig-upms
    image: pig-upms
    environment:
      MYSQL_HOST: pig-mysql
      REDIS_HOST: pig-redis
      NACOS_HOST: pig-register
    depends_on:
      pig-mysql:
        condition: service_healthy
      pig-redis:
        condition: service_started
      pig-register:
        condition: service_started
    networks:
      - spring_cloud_default

  pig-media:
    build:
      context: ./pig-media/pig-media-biz
    restart: always
    container_name: pig-media
    hostname: pig-media
    image: pig-media
    environment:
      MYSQL_HOST: pig-mysql
      REDIS_HOST: pig-redis
      NACOS_HOST: pig-register
    depends_on:
      pig-mysql:
        condition: service_healthy
      pig-redis:
        condition: service_started
      pig-register:
        condition: service_started
    networks:
      - spring_cloud_default

  pig-monitor:
    build:
      context: ./pig-visual/pig-monitor
    restart: always
    ports:
      - 5001:5001
    container_name: pig-monitor
    hostname: pig-monitor
    image: pig-monitor
    environment:
      NACOS_HOST: pig-register
    depends_on:
      pig-register:
        condition: service_started
    networks:
      - spring_cloud_default

  pig-codegen:
    build:
      context: ./pig-visual/pig-codegen
    restart: always
    container_name: pig-codegen
    hostname: pig-codegen
    image: pig-codegen
    environment:
      MYSQL_HOST: pig-mysql
      REDIS_HOST: pig-redis
      NACOS_HOST: pig-register
    depends_on:
      pig-mysql:
        condition: service_healthy
      pig-redis:
        condition: service_started
      pig-register:
        condition: service_started
    networks:
      - spring_cloud_default

  pig-quartz:
    build:
      context: ./pig-visual/pig-quartz
    restart: always
    image: pig-quartz
    container_name: pig-quartz
    environment:
      MYSQL_HOST: pig-mysql
      REDIS_HOST: pig-redis
      NACOS_HOST: pig-register
    depends_on:
      pig-mysql:
        condition: service_healthy
      pig-redis:
        condition: service_started
      pig-register:
        condition: service_started
    networks:
      - spring_cloud_default

networks:
  spring_cloud_default:
    name:  spring_cloud_default
    driver: bridge
